# https://github.com/linuxserver/docker-code-server

apiVersion: v1
kind: Namespace
metadata:
  name: code-server

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: code-server
  namespace: code-server
spec:
  rules:
    - host: code.example.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: code-server
                port:
                  number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: code-server
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: code-server

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-config
  namespace: code-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code-server
  name: code-server
  namespace: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  replicas: 1
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
        - image: ghcr.io/sergeykorablin/code-server-python:latest
          imagePullPolicy: Always
          name: code-server
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: code-secrets
                  key: password
            - name: SUDO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: code-secrets
                  key: sudo_password
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: PORT
              value: "8080"
            - name: TZ
              value: Europe/Moscow
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: code-config
