name: Build and Push Docker image

on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Extract tag without 'v'
        id: extract_tag
        run: echo "::set-output name=tag_without_v::${GITHUB_REF#refs/tags/v}"
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          tags: |
            ghcr.io/sergeykorablin/code-server-python:latest
            ghcr.io/sergeykorablin/code-server-python:${{ steps.extract_tag.outputs.tag_without_v }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: "ghcr.io/sergeykorablin/code-server-python:${{ steps.extract_tag.outputs.tag_without_v }}"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/sergeykorablin/code-server-python:latest
            ghcr.io/sergeykorablin/code-server-python:${{ steps.extract_tag.outputs.tag_without_v }}
                
