name: Version update
on:
  schedule:
    - cron: "0 1 * * *"
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - name: Update Dockerfile
        run: |
          VERSION=$(curl -s https://api.github.com/repos/linuxserver/docker-code-server/releases/latest | jq -r '.tag_name' | sed -E 's/([0-9]+\.[0-9]+\.[0-9]+)-.*/\1/')

          if grep -q "FROM linuxserver/code-server:$VERSION" Dockerfile; then
            echo "Version $VERSION is already used in Dockerfile."
            exit 0
          else
            sed -i "s/FROM linuxserver\/code-server:.*/FROM linuxserver\/code-server:$VERSION/" Dockerfile
            git config --local user.email github-actions@github.com
            git config --local user.name gitHub-actions
            git add Dockerfile
            git commit -m "Update code-server version to $VERSION"
            git tag $VERSION
            git push origin main --tags
          fi
